# Generated by Django 5.0.3 on 2024-04-07 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_locations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='named_location',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique coordinates'),
        ),
    ]
