# Generated by Django 5.0.3 on 2024-04-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('named_locations_app', '0002_named_location_unique_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='named_location',
            old_name='state',
            new_name='country',
        ),
    ]
