# Generated by Django 5.0.3 on 2024-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('named_locations_app', '0003_rename_state_named_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='named_location',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='named_location',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
