FROM node:alpine AS builder

WORKDIR /aviation-weather-hub/frontend

RUN apk add --no-cache python3 make g++ \
    && ln -sf python3 /usr/bin/python

COPY package*.json /aviation-weather-hub/frontend/

RUN npm install

COPY . /aviation-weather-hub/frontend/

CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]