# Generated by Django 5.0.3 on 2024-04-13 15:59

import airport_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0002_alter_airport_icao_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), airport_app.validators.validate_icao_code]),
        ),
    ]
