# Generated by Django 5.0.3 on 2024-04-04 16:20

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=50, validators=[user_app.validators.validate_display_name]),
        ),
    ]
