# Generated by Django 5.0.3 on 2024-04-04 16:24

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, validators=[user_app.validators.validate_full_name]),
        ),
    ]
