# Generated by Django 5.0.3 on 2024-04-07 03:23

import django.core.validators
import django.db.models.deletion
import location_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), location_app.validators.validate_icao_code])),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), location_app.validators.validate_airport_name])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Named_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(1), location_app.validators.validate_city_name])),
                ('state', models.CharField(max_length=2, validators=[location_app.validators.validate_state_abbreviation])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
