# Generated by Django 5.0.3 on 2024-04-07 21:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import flight_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('aircraft_type_model', models.CharField(max_length=20, validators=[flight_app.validators.validate_aircraft_type_model])),
                ('pilot_responsible', models.CharField(max_length=100, validators=[flight_app.validators.validate_pilot_responsible])),
                ('origin', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), flight_app.validators.validate_origin])),
                ('destination', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), flight_app.validators.validate_destination])),
                ('flight_level', models.PositiveIntegerField(default=1000)),
                ('takeoff_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_time', models.DateTimeField()),
                ('brief_time', models.DateTimeField()),
                ('void_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('tail_number', 'aircraft_type_model', 'takeoff_time'), name='unique_aircraft_takeoff_time'),
        ),
    ]
