# Generated by Django 5.0.3 on 2024-04-07 22:58

import django.core.validators
import django.db.models.deletion
import flight_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_alter_flight_tail_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='brief_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='void_time',
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_winds', models.CharField(max_length=10, validators=[flight_app.validators.validate_surface_winds])),
                ('flight_level_winds', models.CharField(max_length=10, validators=[flight_app.validators.validate_flight_level_winds])),
                ('visibility', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(3), flight_app.validators.validate_visibility])),
                ('sky_condition', models.CharField(max_length=50, validators=[flight_app.validators.validate_sky_condition])),
                ('temperature', models.CharField(max_length=4, validators=[flight_app.validators.validate_temperature])),
                ('altimeter_setting', models.CharField(max_length=5, validators=[flight_app.validators.validate_altimeter_setting])),
                ('brief_time', models.DateTimeField()),
                ('void_time', models.DateTimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='flight_app.flight')),
            ],
        ),
    ]
