# Generated by Django 5.0.3 on 2024-04-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_remove_flight_brief_time_remove_flight_void_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='brief_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
