# Generated by Django 5.0.3 on 2024-04-08 01:18

import django.db.models.deletion
import flight_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0004_alter_brief_brief_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True, validators=[flight_app.validators.validate_hazard_type])),
                ('information', models.TextField(default='unknown')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='flight_app.brief')),
            ],
        ),
    ]
