# Generated by Django 5.0.3 on 2024-04-11 15:56

import django.core.validators
import flight_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0005_hazard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='callsign',
            field=models.CharField(default='SHADY29', max_length=20, validators=[django.core.validators.MinLengthValidator(1), flight_app.validators.validate_callsign]),
            preserve_default=False,
        ),
    ]
