# Generated by Django 5.0.3 on 2024-04-15 19:06

import flight_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0006_flight_callsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='type',
            field=models.CharField(max_length=30, validators=[flight_app.validators.validate_hazard_type]),
        ),
    ]
