# Generated by Django 5.0.3 on 2024-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0007_alter_hazard_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hazard',
            constraint=models.UniqueConstraint(fields=('brief', 'type'), name='unique type per brief'),
        ),
    ]
