# Generated by Django 5.0.3 on 2024-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0008_hazard_unique_type_per_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='brief_time',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='brief',
            constraint=models.UniqueConstraint(fields=('flight', 'brief_time'), name='unique brief time per flight'),
        ),
    ]
