name: Cypress e2e Tests
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autotesting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose
      - name: Build and start containers
        run: docker-compose -f docker-compose-dev.yml up -d
      - name: Make migrations
        run: |
          docker-compose exec -T gunicorn python ./back-end/manage.py makemigrations
          docker-compose exec -T gunicorn python ./back-end/manage.py migrate
      - name: Load fixtures
        run: |
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/user_app/fixtures/users.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/airport_app/fixtures/airports.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/named_locations_app/fixtures/named_locations.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/flight_app/fixtures/flights.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/flight_app/fixtures/briefs.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/flight_app/fixtures/hazards.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/list_app/fixtures/lists.json
          docker-compose exec -T gunicorn python ./back-end/manage.py loaddata ./back-end/list_app/fixtures/tasks.json
      - name: Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: docker-compose exec -T frontend npm run dev
          working-directory: front-end
        continue-on-error: true
