name: Cypress e2e Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd ./front-end
          npm ci
      - name: Run cypress tests
        run: |
          cd ./front-end
          npx cypress run --spec cypress/e2e
