name: Django CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autotesting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose
      - name: Build and start containers
        run: docker-compose -f docker-compose-dev.yml up -d
      - name: Run User Model Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_user_models
      - name: Run List App Model Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_list_models
      - name: Run Airport Model Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_airport_models
      - name: Run Named_location Model Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_named_locations_models
      - name: Run Flight App Model Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_flight_models
      - name: Run User View Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_user_views
      - name: Run List App View Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_list_views
      - name: Run Airport View Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_airport_views
      - name: Run Named_location View Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_named_locations_views
      - name: Run Flight View Tests
        run: docker-compose exec -T gunicorn python ./back-end/manage.py test tests.test_flight_views
