name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autotesting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql -y
          sudo apt-get install postgresql-contrib -y
          sudo apt-get install postgresql-client -y
          echo waiting...
          sleep 6
          sudo service postgresql start
          sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"CREATE USER runner WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '';\""
          sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"create database weather_db;\""
          echo finished pg commands...
          sudo service postgresql restart
      - name: Set up Python
        run: |
          sudo apt install python3
          sudo apt-get install python3-pip
      - name: Install Dependencies
        run: |
          pip install -r ./back-end/requirements.txt
      - name: Migrations
        run: |
          python ./back-end/manage.py makemigrations
          python ./back-end/manage.py migrate
      - name: Run Tests
        run: |
          python ./back-end/manage.py test tests.test_user_models
          python ./back-end/manage.py test tests.test_list_models
          python ./back-end/manage.py test tests.test_airport_models
          python ./back-end/manage.py test tests.test_named_locations_models
          python ./back-end/manage.py test tests.test_user_views
          python ./back-end/manage.py test tests.test_list_views
          python ./back-end/manage.py test tests.test_airport_views
          pyhton ./back-end/manage.py test tests.test_named_locations_views
