name: python-linter

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./back-end/requirements.txt
      
      - name: Run Pylint
        run: |
          cd ./back-end
          shopt -s globstar
          pylint --load-plugins pylint_django --django-settings-module=weather_proj.settings **/*.py --ignore-paths='^user_app/migrations/.*$','^airport_app/migrations/.*$','^coordinate_app/migrations/.*$','^flight_app/migrations/.*$','^list_app/migrations/.*$','^metar_app/migrations/.*$','^named_locations_app/migrations/.*$','^taf_app/migrations/.*$','^tests/.*$' --fail-under=9.0 || exit 0